import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {ReposProvider} from "@/app/context/repos.context";
import {Toaster} from "@/components/ui/toaster";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Performance test',
  description: 'Generated by create next app',
  appLinks: {
    web: {
      url: "https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css",
    }
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR" className={"dark subpixel-antialiased"}>
      <ReposProvider >
        <body className={inter.className}>
            {children}
          <Toaster />
        </body>
      </ReposProvider>
    </html>
  )
}
